### ISSUE TITLE
Use prettify to make the code readable

### ISSUE THREAD

**Issue by balupton** [dado3212/iTunesToSpotify#1]

**Comment by dado3212** [comment]
Which part isn’t readable?

**Comment by balupton** [comment]
The indentation of this file (happened to be the first that I opened) is all over the place:
https://github.com/dado3212/iTunesToSpotify/blob/master/js/main.js

**Comment by dado3212** [comment]
Looks fine to me.  Thanks for the suggestion though!

**Comment by balupton** [comment]
Strange. Maybe it was an issue with how GitHub rendered it as refreshing the page, fixed the problem.

<img width="794" alt="screen shot 2019-01-23 at 6 06 25 pm" src="https://user-images.githubusercontent.com/61148/51588991-bd3d0300-1f39-11e9-957d-a6c45068b45d.png">
<img width="672" alt="screen shot 2019-01-23 at 6 06 13 pm" src="https://user-images.githubusercontent.com/61148/51588992-bd3d0300-1f39-11e9-8d0a-5dda2ef217c7.png">
