### ISSUE TITLE
Use travis-ci and surge.sh to deploy the dist folder

### ISSUE THREAD

**Issue by balupton** [dado3212/iTunesToSpotify#2]
You can use https://github.com/bevry/awesome-travis/blob/master/scripts/surge.bash to have each commit, branch, and tag pushed to surge.sh. You should have your build step be the linting, and build. That way surge will deploy the build.

Then you can run a command to trim `dist` from the git history, to make cloning this repository not a 200mb adventure.

**Comment by dado3212** [comment]
Don't have any desire to pay for Travis-CI, so the build steps for now are fine for me, given that this was a one off project for someone.  I reduced the dist folder so that it's only a 100mb adventure, and with a lot fewer files, so the checkout process is a little better.

**Comment by balupton** [comment]
Travis is free for open-source projects
